### ISSUE TITLE
Warning message: In plot.aggr(res, ...) : not enough horizontal space to display frequencies

### ISSUE THREAD

**Issue by duttashi** [duttashi/learnr#7]
When plotting missing data using the `VIM` package, I got the following warning message;
`Warning message: In plot.aggr(res, ...) : not enough horizontal space to display frequencies`

**Comment by duttashi** [comment]
Solution: See this [SO post](https://stackoverflow.com/questions/34347540/not-enough-horizontal-space-to-display-frequencies)

Step 1: Create a custom function like

```
> resetPar <- function() {
  dev.new()
  op <- par(no.readonly = TRUE)
  dev.off()
  op
}
```
Step 2: Execute `> par(resetPar())`

If `> par(resetPar())` does not solve the problem, then in the `aggr_plot()` set `cex.numbers()` to a value less than `1`. See the following example

```
> library(VIM)
> aggr_plot <- aggr(dengue.train, col=c('navyblue','red'), numbers=TRUE, sortVars=TRUE, 
                  labels=names(dengue.train), gap=3, cex.axis=.3,cex.numbers=0.3,
                  ylab=c("Histogram of missing data","Pattern")
                  )

```

**Comment by khemanta** [comment]
if you are  getting error in print or plot use the warning=F in  r-code chunk or in global option.

```{r, warning=F}
# your r-code chunk goes here.
```
